---
apiVersion: v1
kind: List
items:
- apiVersion: tsb.tetrate.io/v2
  kind: Workspace
  metadata:
    name: bookinfo-ws
    annotations:
      tsb.tetrate.io/organization: tetrate
      tsb.tetrate.io/tenant: tetrate
  spec:
    namespaceSelector:
      names:
      - "c1/bookinfo"

